is_simulation: ${IS_SIMULATION:True}
argos:
    hostname: ${ARGOS_HOSTNAME:localhost}
    port_start: 9850
    port_end: 9860
database:
    connection_string: ${DB_CONNECTION_STRING:mongodb://local:lacol@localhost:5002/}
    name: ${DB_NAME:server}
mapping:
    trigger_distance: 5.0
    duplicate_distance: 0.5
clients:
    uri_start: 0
    uri_end: 2
    drones:
        update_time: 2.0
        default_z: 0.5
        trigger_distance: 0.3
remote_compiler:
    connection_string: ${REMOTE_COMPILER_CONNECTION_STRING:localhost:5003}
grpc:
    connection_timeout: 1
