services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=lacol
    volumes:
      - mongoVolume:/data/db
    ports:
      - 5002:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: local
      ME_CONFIG_MONGODB_ADMINPASSWORD: lacol
      ME_CONFIG_MONGODB_URL: mongodb://local:lacol@mongodb:27017/

volumes:
  mongoVolume: {}
